<?xml version="1.0" encoding="utf-8"?>
<!-- generator="Joomla! - Open Source Content Management" -->
<feed xmlns="http://www.w3.org/2005/Atom"  xml:lang="pt-br">
	<title type="text">Catálogo Virtual</title>
	<subtitle type="text"></subtitle>
	<link rel="alternate" type="text/html" href="http://localhost"/>
	<id>http://localhost/catalogovirtual_teste/index.php</id>
	<updated>2026-02-05T21:58:52+00:00</updated>
	<generator uri="http://joomla.org" version="2.5">Joomla! - Open Source Content Management</generator>
	<link rel="self" type="application/atom+xml" href="http://localhost/catalogovirtual_teste/index.php?format=feed&amp;type=atom"/>
	<entry>
		<title>Taller ILAM</title>
		<link rel="alternate" type="text/html" href="http://localhost/catalogovirtual_teste/index.php/9-uncategorised/95-taller-ilam"/>
		<published>2013-08-03T08:03:24+00:00</published>
		<updated>2013-08-03T08:03:24+00:00</updated>
		<id>http://localhost/catalogovirtual_teste/index.php/9-uncategorised/95-taller-ilam</id>
		<author>
			<name>Super User</name>
			<email>lusans@gmail.com</email>
		</author>
		<summary type="html">&lt;div class=&quot;feed-description&quot;&gt;&lt;div style=&quot;text-align: center;&quot;&gt;
&lt;div data-configid=&quot;3037710/4284534&quot; style=&quot;width: 650px; height: 445px;&quot; class=&quot;issuuembed&quot;&gt;&lt;/div&gt;&lt;script type=&quot;text/javascript&quot; src=&quot;//e.issuu.com/embed.js&quot; async=&quot;true&quot;&gt;&lt;/script&gt;
&lt;/div&gt;&lt;/div&gt;</summary>
		<content type="html">&lt;div class=&quot;feed-description&quot;&gt;&lt;div style=&quot;text-align: center;&quot;&gt;
&lt;div data-configid=&quot;3037710/4284534&quot; style=&quot;width: 650px; height: 445px;&quot; class=&quot;issuuembed&quot;&gt;&lt;/div&gt;&lt;script type=&quot;text/javascript&quot; src=&quot;//e.issuu.com/embed.js&quot; async=&quot;true&quot;&gt;&lt;/script&gt;
&lt;/div&gt;&lt;/div&gt;</content>
		<category term="Destaque" />
		<category term="Uncategorised" />
	</entry>
	<entry>
		<title>&quot;Más Allá&quot; IV Bienal Internacional de Grabado ICPNA</title>
		<link rel="alternate" type="text/html" href="http://localhost/catalogovirtual_teste/index.php/9-uncategorised/94-catalogo-virtual-mas-alla-iv-bienal-internacional-de-grabado-icpna"/>
		<published>2013-08-03T02:33:27+00:00</published>
		<updated>2013-08-03T02:33:27+00:00</updated>
		<id>http://localhost/catalogovirtual_teste/index.php/9-uncategorised/94-catalogo-virtual-mas-alla-iv-bienal-internacional-de-grabado-icpna</id>
		<author>
			<name>Super User</name>
			<email>lusans@gmail.com</email>
		</author>
		<summary type="html">&lt;div class=&quot;feed-description&quot;&gt;&lt;div style=&quot;text-align: center;&quot;&gt;&amp;nbsp;&lt;/div&gt;
&lt;div style=&quot;text-align: center;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;&lt;strong&gt;&amp;nbsp;&lt;/strong&gt;&lt;/span&gt;&lt;/div&gt;
&lt;div style=&quot;text-align: center;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;&lt;strong&gt;Paulo Cheida é destaque na IV Bienal Internacional do Peru&lt;/strong&gt;&lt;/span&gt;&lt;/div&gt;
&lt;div style=&quot;text-align: center;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;&lt;strong&gt;&amp;nbsp;&lt;/strong&gt;&lt;/span&gt;&lt;/div&gt;
&lt;div style=&quot;text-align: left;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;&lt;strong&gt;{besps}slide/2013/icpna{/besps}&lt;/strong&gt;&lt;/span&gt;&lt;/div&gt;
&lt;div style=&quot;text-align: center;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;&lt;strong&gt;&amp;nbsp;&amp;nbsp;&lt;/strong&gt;&lt;/span&gt;&lt;/div&gt;
&lt;div&gt;O artista brasileiro Paulo Cheida Sans é um dos principais destaques na “IV Bienal Internacional de Grabado” realizada pelo ICPNA – Instituto Cultural Peruano Norte Americano - em Lima, Peru. O evento, aberto em 28 de maio, reúne 20 exposições distribuídas em 16 galerias e espaços culturais, além de conferências, oficinas de criação e visitas guiadas que acontecem até julho.&lt;/div&gt;
&lt;div&gt;&amp;nbsp;&lt;/div&gt;
&lt;div&gt;A curadoria desta quarta edição é dos especialistas Juan Peralta e Daniel Contreras, que reuniram a participação de representantes de 10 países: Argentina, Brasil, Bolívia, Colômbia, Chile, Espanha, Estados Unidos, México, Uruguai e Peru. O tema do evento &quot;Transferencia: Imagen de la memoria&quot; fomenta , preserva e difunde a arte da gravura e as novas possibilidades criativas.&lt;/div&gt;
&lt;div&gt;&amp;nbsp;&lt;br /&gt;Paulo Cheida participa da mostra “Más Allá: Otredad en el grabado contemporâneo” na Galería Germán Krüger Espantoso - ICPNA Miraflores. Esta mostra reúne gravadores de nível internacional e é uma das exposições centrais da Bienal. Além de Cheida, representando o Brasil, participam: Alicia Candiani (Argentina), Enrique Pérez e o TEBAC (México), Colectivo Carrier Pigeon (EE.UU.), Pablo Uribe (Uruguai), Ricardo Villarroel (Chile) e Alfredo Márquez (Perú).&lt;/div&gt;
&lt;div&gt;
&lt;p&gt;&amp;nbsp;&amp;nbsp;&lt;/p&gt;
Paulo Cheida apresenta um conjunto de obras intitulado “Nexos Causais”, composto por 10 gravuras em linóleo, 1 painel de grande formato com técnica mista de gravura e uma peça tridimensional de gravura expandida. Cheida explica que em suas obras “há uma denúncia e repúdio contra a busca incessante e perpetuação inescrupulosa do ‘poder’ na sociedade, onde opressores brincam e conduzem as brincadeiras e os oprimidos indefesos aceitam as ‘regras’ de uma convivência injusta e manipuladora”. O artista proferiu conferência com o tema “Presencia del grabado en el arte contemporâneo” e suas gravuras estão estampadas em banners e no painel de entrada da Galeria do ICPNA Miraflores.&lt;/div&gt;
&lt;div&gt;&amp;nbsp;&lt;br /&gt;Paulo de Tarso Cheida Sans nasceu em Campinas, SP (1955). Cursou Artes Plásticas na Pontifícia Universidade Católica de Campinas (1978) e é Doutor em Artes pela Unicamp – Universidade Estadual de Campinas (2009). Participou em mais de 400 exposições, tendo recebido 41 prêmios em salões de arte no Brasil e três no exterior (Portugal, Estados Unidos e França). É professor do curso de Artes Visuais e extensionista da PUC-Campinas. Juntamente com a artista Celina Carvalho, fundou o Museu Olho Latino, sediado em Atibaia, SP, especializado na arte da gravura. É curador de exposições nacionais e internacionais e autor de livros na área de Artes.&lt;/div&gt;
&lt;div&gt;&amp;nbsp;&lt;br /&gt;A Bienal Internacional de Grabado do Peru é um dos principais eventos na área da arte da gravura dada a sua grandiosidade e qualidade das exposições. Confira o site oficial da Bienal:&amp;nbsp;&lt;a href=&quot;http://www6.icpna.edu.pe/interior.aspx?cod_1=53&amp;amp;cod_2=588&quot;&gt;&amp;nbsp;&lt;/a&gt;&lt;a href=&quot;http://www6.icpna.edu.pe/interior.aspx?cod_1=53&amp;amp;cod_2=588&quot; target=&quot;_blank&quot;&gt;ICPNA&lt;/a&gt;&amp;nbsp;&lt;/div&gt;
&lt;div&gt;&amp;nbsp;&amp;nbsp;&lt;/div&gt;
&lt;div&gt;&lt;hr /&gt;&amp;nbsp;&lt;/div&gt;
&lt;div&gt;Obras do Acervo Olho Latino que participam desta mostra:&lt;/div&gt;
&lt;div&gt;&amp;nbsp;&lt;/div&gt;
&lt;div&gt;
&lt;p&gt;&lt;a href=&quot;index.php?option=com_content&amp;amp;view=article&amp;amp;id=84:a-borboleta-e-os-confetes&amp;amp;catid=90:gravuras&quot;&gt;&lt;img src=&quot;images/5_A_Borboleta_e_os_confetes.jpg&quot; alt=&quot;5 A Borboleta e os confetes&quot; width=&quot;150&quot; height=&quot;71&quot; /&gt;&lt;/a&gt;&amp;nbsp;|&amp;nbsp;&lt;a href=&quot;index.php?option=com_content&amp;amp;view=article&amp;amp;id=85:cena-iluminada&amp;amp;catid=90:gravuras&quot;&gt;&lt;img src=&quot;images/6_cena_iluminada.jpg&quot; alt=&quot;6 cena iluminada&quot; width=&quot;125&quot; height=&quot;89&quot; /&gt;&lt;/a&gt;&amp;nbsp;|&amp;nbsp;&lt;a href=&quot;index.php?option=com_content&amp;amp;view=article&amp;amp;id=83:dominantes-e-dominados&amp;amp;catid=90:gravuras&quot;&gt;&lt;img src=&quot;images/3_dominantes_e_dominados.jpg&quot; alt=&quot;3 dominantes e dominados&quot; width=&quot;150&quot; height=&quot;74&quot; /&gt;&lt;/a&gt;&amp;nbsp;|&amp;nbsp;&lt;a href=&quot;index.php?option=com_content&amp;amp;view=article&amp;amp;id=88:renascer&amp;amp;catid=90:gravuras&quot;&gt;&lt;img src=&quot;images/10_Renascer.jpg&quot; alt=&quot;10 Renascer&quot; width=&quot;125&quot; height=&quot;94&quot; /&gt;&lt;/a&gt;&lt;/p&gt;
&lt;p&gt;&lt;a href=&quot;index.php?option=com_content&amp;amp;view=article&amp;amp;id=84:a-borboleta-e-os-confetes&amp;amp;catid=90:gravuras&quot;&gt;&amp;nbsp;A Borboleta e os Confetes&lt;/a&gt; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp;&lt;a href=&quot;index.php?option=com_content&amp;amp;view=article&amp;amp;id=85:cena-iluminada&amp;amp;catid=90:gravuras&quot;&gt;Cena Iluminada&lt;/a&gt; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp;&lt;a href=&quot;index.php?option=com_content&amp;amp;view=article&amp;amp;id=83:dominantes-e-dominados&amp;amp;catid=90:gravuras&quot;&gt;Dominantes e Dominados&lt;/a&gt; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &lt;a href=&quot;index.php?option=com_content&amp;amp;view=article&amp;amp;id=88:renascer&amp;amp;catid=90:gravuras&quot;&gt;Renascer&lt;/a&gt;&lt;br /&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;a href=&quot;index.php?option=com_content&amp;amp;view=article&amp;amp;id=72:na-terra-das-bananas&amp;amp;catid=90:gravuras&quot;&gt;&lt;img src=&quot;images/9_Na_Terra_das_Bananas.jpg&quot; alt=&quot;9 Na Terra das Bananas&quot; width=&quot;140&quot; height=&quot;84&quot; /&gt;&lt;/a&gt;&amp;nbsp;| &lt;a href=&quot;index.php?option=com_content&amp;amp;view=article&amp;amp;id=86:os-cacadores&amp;amp;catid=90:gravuras&quot;&gt;&lt;img src=&quot;images/7_os_cacadores.jpg&quot; alt=&quot;7 os caçadores&quot; width=&quot;140&quot; height=&quot;86&quot; /&gt;&lt;/a&gt;&amp;nbsp;| &lt;a href=&quot;index.php?option=com_content&amp;amp;view=article&amp;amp;id=87:os-imigrantes&amp;amp;catid=90:gravuras&quot;&gt;&lt;img src=&quot;images/8_Os_imigrantes.jpg&quot; alt=&quot;8 Os imigrantes&quot; width=&quot;150&quot; height=&quot;73&quot; /&gt;&lt;/a&gt;&amp;nbsp;|&amp;nbsp;&lt;a href=&quot;index.php?option=com_content&amp;amp;view=article&amp;amp;id=82:tres-passaros&amp;amp;catid=90:gravuras&quot;&gt;&lt;img src=&quot;images/4Tres_passaros.jpg&quot; alt=&quot;4Tres passaros&quot; width=&quot;150&quot; height=&quot;74&quot; /&gt;&lt;/a&gt;&lt;br /&gt;&amp;nbsp; &amp;nbsp; &lt;a href=&quot;index.php?option=com_content&amp;amp;view=article&amp;amp;id=72:na-terra-das-bananas&amp;amp;catid=90:gravuras&quot;&gt;Na Terra das Bananas&lt;/a&gt; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &lt;a href=&quot;index.php?option=com_content&amp;amp;view=article&amp;amp;id=86:os-cacadores&amp;amp;catid=90:gravuras&quot;&gt;Os Caçadores&lt;/a&gt; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp;&lt;a href=&quot;index.php?option=com_content&amp;amp;view=article&amp;amp;id=87:os-imigrantes&amp;amp;catid=90:gravuras&quot;&gt;Os Imigrantes&lt;/a&gt; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &lt;a href=&quot;index.php?option=com_content&amp;amp;view=article&amp;amp;id=82:tres-passaros&amp;amp;catid=90:gravuras&quot;&gt;Três Pássaros&lt;/a&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&amp;nbsp; &amp;nbsp; &amp;nbsp;&lt;a href=&quot;index.php?option=com_content&amp;amp;view=article&amp;amp;id=81:o-comedor-de-banana&amp;amp;catid=90:gravuras&quot;&gt;&lt;img src=&quot;images/2O_comedor_de_banana.jpg&quot; alt=&quot;2O comedor de banana&quot; width=&quot;90&quot; height=&quot;224&quot; /&gt;&lt;/a&gt;&amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; | &amp;nbsp; &amp;nbsp; &lt;a href=&quot;index.php?option=com_content&amp;amp;view=article&amp;amp;id=80:o-vaso-do-desejo&amp;amp;catid=90:gravuras&quot;&gt;&lt;img src=&quot;images/1_VasoDo_Desejo.jpg&quot; alt=&quot;1 VasoDo Desejo&quot; width=&quot;100&quot; height=&quot;217&quot; /&gt;&lt;/a&gt;&amp;nbsp; &amp;nbsp; &amp;nbsp;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;a href=&quot;index.php?option=com_content&amp;amp;view=article&amp;amp;id=81:o-comedor-de-banana&amp;amp;catid=90:gravuras&quot;&gt;O Comedor de Banana&lt;/a&gt; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp;&lt;a href=&quot;index.php?option=com_content&amp;amp;view=article&amp;amp;id=80:o-vaso-do-desejo&amp;amp;catid=90:gravuras&quot;&gt;O Vaso do Desejo&lt;/a&gt;&lt;br /&gt;&lt;br /&gt;&amp;nbsp;&lt;/p&gt;
&lt;/div&gt;&lt;/div&gt;</summary>
		<content type="html">&lt;div class=&quot;feed-description&quot;&gt;&lt;div style=&quot;text-align: center;&quot;&gt;&amp;nbsp;&lt;/div&gt;
&lt;div style=&quot;text-align: center;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;&lt;strong&gt;&amp;nbsp;&lt;/strong&gt;&lt;/span&gt;&lt;/div&gt;
&lt;div style=&quot;text-align: center;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;&lt;strong&gt;Paulo Cheida é destaque na IV Bienal Internacional do Peru&lt;/strong&gt;&lt;/span&gt;&lt;/div&gt;
&lt;div style=&quot;text-align: center;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;&lt;strong&gt;&amp;nbsp;&lt;/strong&gt;&lt;/span&gt;&lt;/div&gt;
&lt;div style=&quot;text-align: left;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;&lt;strong&gt;{besps}slide/2013/icpna{/besps}&lt;/strong&gt;&lt;/span&gt;&lt;/div&gt;
&lt;div style=&quot;text-align: center;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;&lt;strong&gt;&amp;nbsp;&amp;nbsp;&lt;/strong&gt;&lt;/span&gt;&lt;/div&gt;
&lt;div&gt;O artista brasileiro Paulo Cheida Sans é um dos principais destaques na “IV Bienal Internacional de Grabado” realizada pelo ICPNA – Instituto Cultural Peruano Norte Americano - em Lima, Peru. O evento, aberto em 28 de maio, reúne 20 exposições distribuídas em 16 galerias e espaços culturais, além de conferências, oficinas de criação e visitas guiadas que acontecem até julho.&lt;/div&gt;
&lt;div&gt;&amp;nbsp;&lt;/div&gt;
&lt;div&gt;A curadoria desta quarta edição é dos especialistas Juan Peralta e Daniel Contreras, que reuniram a participação de representantes de 10 países: Argentina, Brasil, Bolívia, Colômbia, Chile, Espanha, Estados Unidos, México, Uruguai e Peru. O tema do evento &quot;Transferencia: Imagen de la memoria&quot; fomenta , preserva e difunde a arte da gravura e as novas possibilidades criativas.&lt;/div&gt;
&lt;div&gt;&amp;nbsp;&lt;br /&gt;Paulo Cheida participa da mostra “Más Allá: Otredad en el grabado contemporâneo” na Galería Germán Krüger Espantoso - ICPNA Miraflores. Esta mostra reúne gravadores de nível internacional e é uma das exposições centrais da Bienal. Além de Cheida, representando o Brasil, participam: Alicia Candiani (Argentina), Enrique Pérez e o TEBAC (México), Colectivo Carrier Pigeon (EE.UU.), Pablo Uribe (Uruguai), Ricardo Villarroel (Chile) e Alfredo Márquez (Perú).&lt;/div&gt;
&lt;div&gt;
&lt;p&gt;&amp;nbsp;&amp;nbsp;&lt;/p&gt;
Paulo Cheida apresenta um conjunto de obras intitulado “Nexos Causais”, composto por 10 gravuras em linóleo, 1 painel de grande formato com técnica mista de gravura e uma peça tridimensional de gravura expandida. Cheida explica que em suas obras “há uma denúncia e repúdio contra a busca incessante e perpetuação inescrupulosa do ‘poder’ na sociedade, onde opressores brincam e conduzem as brincadeiras e os oprimidos indefesos aceitam as ‘regras’ de uma convivência injusta e manipuladora”. O artista proferiu conferência com o tema “Presencia del grabado en el arte contemporâneo” e suas gravuras estão estampadas em banners e no painel de entrada da Galeria do ICPNA Miraflores.&lt;/div&gt;
&lt;div&gt;&amp;nbsp;&lt;br /&gt;Paulo de Tarso Cheida Sans nasceu em Campinas, SP (1955). Cursou Artes Plásticas na Pontifícia Universidade Católica de Campinas (1978) e é Doutor em Artes pela Unicamp – Universidade Estadual de Campinas (2009). Participou em mais de 400 exposições, tendo recebido 41 prêmios em salões de arte no Brasil e três no exterior (Portugal, Estados Unidos e França). É professor do curso de Artes Visuais e extensionista da PUC-Campinas. Juntamente com a artista Celina Carvalho, fundou o Museu Olho Latino, sediado em Atibaia, SP, especializado na arte da gravura. É curador de exposições nacionais e internacionais e autor de livros na área de Artes.&lt;/div&gt;
&lt;div&gt;&amp;nbsp;&lt;br /&gt;A Bienal Internacional de Grabado do Peru é um dos principais eventos na área da arte da gravura dada a sua grandiosidade e qualidade das exposições. Confira o site oficial da Bienal:&amp;nbsp;&lt;a href=&quot;http://www6.icpna.edu.pe/interior.aspx?cod_1=53&amp;amp;cod_2=588&quot;&gt;&amp;nbsp;&lt;/a&gt;&lt;a href=&quot;http://www6.icpna.edu.pe/interior.aspx?cod_1=53&amp;amp;cod_2=588&quot; target=&quot;_blank&quot;&gt;ICPNA&lt;/a&gt;&amp;nbsp;&lt;/div&gt;
&lt;div&gt;&amp;nbsp;&amp;nbsp;&lt;/div&gt;
&lt;div&gt;&lt;hr /&gt;&amp;nbsp;&lt;/div&gt;
&lt;div&gt;Obras do Acervo Olho Latino que participam desta mostra:&lt;/div&gt;
&lt;div&gt;&amp;nbsp;&lt;/div&gt;
&lt;div&gt;
&lt;p&gt;&lt;a href=&quot;index.php?option=com_content&amp;amp;view=article&amp;amp;id=84:a-borboleta-e-os-confetes&amp;amp;catid=90:gravuras&quot;&gt;&lt;img src=&quot;images/5_A_Borboleta_e_os_confetes.jpg&quot; alt=&quot;5 A Borboleta e os confetes&quot; width=&quot;150&quot; height=&quot;71&quot; /&gt;&lt;/a&gt;&amp;nbsp;|&amp;nbsp;&lt;a href=&quot;index.php?option=com_content&amp;amp;view=article&amp;amp;id=85:cena-iluminada&amp;amp;catid=90:gravuras&quot;&gt;&lt;img src=&quot;images/6_cena_iluminada.jpg&quot; alt=&quot;6 cena iluminada&quot; width=&quot;125&quot; height=&quot;89&quot; /&gt;&lt;/a&gt;&amp;nbsp;|&amp;nbsp;&lt;a href=&quot;index.php?option=com_content&amp;amp;view=article&amp;amp;id=83:dominantes-e-dominados&amp;amp;catid=90:gravuras&quot;&gt;&lt;img src=&quot;images/3_dominantes_e_dominados.jpg&quot; alt=&quot;3 dominantes e dominados&quot; width=&quot;150&quot; height=&quot;74&quot; /&gt;&lt;/a&gt;&amp;nbsp;|&amp;nbsp;&lt;a href=&quot;index.php?option=com_content&amp;amp;view=article&amp;amp;id=88:renascer&amp;amp;catid=90:gravuras&quot;&gt;&lt;img src=&quot;images/10_Renascer.jpg&quot; alt=&quot;10 Renascer&quot; width=&quot;125&quot; height=&quot;94&quot; /&gt;&lt;/a&gt;&lt;/p&gt;
&lt;p&gt;&lt;a href=&quot;index.php?option=com_content&amp;amp;view=article&amp;amp;id=84:a-borboleta-e-os-confetes&amp;amp;catid=90:gravuras&quot;&gt;&amp;nbsp;A Borboleta e os Confetes&lt;/a&gt; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp;&lt;a href=&quot;index.php?option=com_content&amp;amp;view=article&amp;amp;id=85:cena-iluminada&amp;amp;catid=90:gravuras&quot;&gt;Cena Iluminada&lt;/a&gt; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp;&lt;a href=&quot;index.php?option=com_content&amp;amp;view=article&amp;amp;id=83:dominantes-e-dominados&amp;amp;catid=90:gravuras&quot;&gt;Dominantes e Dominados&lt;/a&gt; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &lt;a href=&quot;index.php?option=com_content&amp;amp;view=article&amp;amp;id=88:renascer&amp;amp;catid=90:gravuras&quot;&gt;Renascer&lt;/a&gt;&lt;br /&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;a href=&quot;index.php?option=com_content&amp;amp;view=article&amp;amp;id=72:na-terra-das-bananas&amp;amp;catid=90:gravuras&quot;&gt;&lt;img src=&quot;images/9_Na_Terra_das_Bananas.jpg&quot; alt=&quot;9 Na Terra das Bananas&quot; width=&quot;140&quot; height=&quot;84&quot; /&gt;&lt;/a&gt;&amp;nbsp;| &lt;a href=&quot;index.php?option=com_content&amp;amp;view=article&amp;amp;id=86:os-cacadores&amp;amp;catid=90:gravuras&quot;&gt;&lt;img src=&quot;images/7_os_cacadores.jpg&quot; alt=&quot;7 os caçadores&quot; width=&quot;140&quot; height=&quot;86&quot; /&gt;&lt;/a&gt;&amp;nbsp;| &lt;a href=&quot;index.php?option=com_content&amp;amp;view=article&amp;amp;id=87:os-imigrantes&amp;amp;catid=90:gravuras&quot;&gt;&lt;img src=&quot;images/8_Os_imigrantes.jpg&quot; alt=&quot;8 Os imigrantes&quot; width=&quot;150&quot; height=&quot;73&quot; /&gt;&lt;/a&gt;&amp;nbsp;|&amp;nbsp;&lt;a href=&quot;index.php?option=com_content&amp;amp;view=article&amp;amp;id=82:tres-passaros&amp;amp;catid=90:gravuras&quot;&gt;&lt;img src=&quot;images/4Tres_passaros.jpg&quot; alt=&quot;4Tres passaros&quot; width=&quot;150&quot; height=&quot;74&quot; /&gt;&lt;/a&gt;&lt;br /&gt;&amp;nbsp; &amp;nbsp; &lt;a href=&quot;index.php?option=com_content&amp;amp;view=article&amp;amp;id=72:na-terra-das-bananas&amp;amp;catid=90:gravuras&quot;&gt;Na Terra das Bananas&lt;/a&gt; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &lt;a href=&quot;index.php?option=com_content&amp;amp;view=article&amp;amp;id=86:os-cacadores&amp;amp;catid=90:gravuras&quot;&gt;Os Caçadores&lt;/a&gt; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp;&lt;a href=&quot;index.php?option=com_content&amp;amp;view=article&amp;amp;id=87:os-imigrantes&amp;amp;catid=90:gravuras&quot;&gt;Os Imigrantes&lt;/a&gt; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &lt;a href=&quot;index.php?option=com_content&amp;amp;view=article&amp;amp;id=82:tres-passaros&amp;amp;catid=90:gravuras&quot;&gt;Três Pássaros&lt;/a&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&amp;nbsp; &amp;nbsp; &amp;nbsp;&lt;a href=&quot;index.php?option=com_content&amp;amp;view=article&amp;amp;id=81:o-comedor-de-banana&amp;amp;catid=90:gravuras&quot;&gt;&lt;img src=&quot;images/2O_comedor_de_banana.jpg&quot; alt=&quot;2O comedor de banana&quot; width=&quot;90&quot; height=&quot;224&quot; /&gt;&lt;/a&gt;&amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; | &amp;nbsp; &amp;nbsp; &lt;a href=&quot;index.php?option=com_content&amp;amp;view=article&amp;amp;id=80:o-vaso-do-desejo&amp;amp;catid=90:gravuras&quot;&gt;&lt;img src=&quot;images/1_VasoDo_Desejo.jpg&quot; alt=&quot;1 VasoDo Desejo&quot; width=&quot;100&quot; height=&quot;217&quot; /&gt;&lt;/a&gt;&amp;nbsp; &amp;nbsp; &amp;nbsp;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;a href=&quot;index.php?option=com_content&amp;amp;view=article&amp;amp;id=81:o-comedor-de-banana&amp;amp;catid=90:gravuras&quot;&gt;O Comedor de Banana&lt;/a&gt; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp;&lt;a href=&quot;index.php?option=com_content&amp;amp;view=article&amp;amp;id=80:o-vaso-do-desejo&amp;amp;catid=90:gravuras&quot;&gt;O Vaso do Desejo&lt;/a&gt;&lt;br /&gt;&lt;br /&gt;&amp;nbsp;&lt;/p&gt;
&lt;/div&gt;&lt;/div&gt;</content>
		<category term="Destaque" />
		<category term="Uncategorised" />
	</entry>
</feed>
