<?php
/**
 * @package   Diametric Template - RocketTheme
 * @version   1.3 January 22, 2013
 * @author    RocketTheme http://www.rockettheme.com
 * @copyright Copyright (C) 2007 - 2012 RocketTheme, LLC
 * @license   http://www.gnu.org/licenses/gpl-2.0.html GNU/GPLv2 only
 *
 * Rockettheme Diametric Template uses the Joomla Framework (http://www.joomla.org), a GNU/GPLv2 content management system
 *
 */
defined('JPATH_BASE') or die();

$gantry_config_mapping = array(
    'belatedPNG' => 'belatedPNG'
);

$gantry_presets = array (
    'presets' => array (
        'preset1' => array (
            'name' => 'Preset 1',
            'logostyle' => 'style1',
            'headerpanel-backgroundcolor' => '#E6E3DE',
            'headerpanel-overlay' => 'light',
            'headerpanel-accentcolor' => '#EF915E',
            'headerpanel-accentoverlay' => 'dark',
            'headerpanel-pattern' => 'paint-splatter',
            'showcasepanel-backgroundcolor' => '#282423',
            'showcasepanel-overlay' => 'dark',
            'showcasepanel-accentcolor' => '#EF915E',
            'showcasepanel-accentoverlay' => 'dark',
            'showcasepanel-pattern' => 'metal',
            'featurepanel-backgroundcolor' => '#9E918C',
            'featurepanel-overlay' => 'light',
            'featurepanel-accentcolor' => '#EF915E',
            'featurepanel-accentoverlay' => 'dark',
            'featurepanel-pattern' => 'leather',
            'menu-overlay' => 'light',
            'body-overlay' => 'light',
            'body-accentcolor' => '#EF915E',
            'body-accentoverlay' => 'dark',
            'footerpanel-backgroundcolor' => '#FF823E',
            'footerpanel-overlay' => 'dark',
            'footerpanel-accentcolor' => '#EF915E',
            'footerpanel-accentoverlay' => 'dark',
            'footerpanel-pattern' => 'leather'
        ),

        'preset2' => array (
            'name' => 'Preset 2',
            'logostyle' => 'style2',
            'headerpanel-backgroundcolor' => '#f0f0f0',
            'headerpanel-overlay' => 'light',
            'headerpanel-accentcolor' => '#2B9DE6',
            'headerpanel-accentoverlay' => 'dark',
            'headerpanel-pattern' => 'noise',
            'showcasepanel-backgroundcolor' => '#2B333F',
            'showcasepanel-overlay' => 'dark',
            'showcasepanel-accentcolor' => '#2B9DE6',
            'showcasepanel-accentoverlay' => 'dark',
            'showcasepanel-pattern' => 'denim',
            'featurepanel-backgroundcolor' => '#ABB3B6',
            'featurepanel-overlay' => 'light',
            'featurepanel-accentcolor' => '#394454',
            'featurepanel-accentoverlay' => 'dark',
            'featurepanel-pattern' => 'textile',
            'menu-overlay' => 'light',
            'body-overlay' => 'light',
            'body-accentcolor' => '#2B9DE6',
            'body-accentoverlay' => 'dark',
            'footerpanel-backgroundcolor' => '#1F75AB',
            'footerpanel-overlay' => 'dark',
            'footerpanel-accentcolor' => '#2B9DE6',
            'footerpanel-accentoverlay' => 'dark',
            'footerpanel-pattern' => 'leather'
        ),

        'preset3' => array (
            'name' => 'Preset 3',
            'logostyle' => 'style3',
            'headerpanel-backgroundcolor' => '#f0f0f0',
            'headerpanel-overlay' => 'light',
            'headerpanel-accentcolor' => '#A3CD65',
            'headerpanel-accentoverlay' => 'dark',
            'headerpanel-pattern' => 'textile',
            'showcasepanel-backgroundcolor' => '#333',
            'showcasepanel-overlay' => 'dark',
            'showcasepanel-accentcolor' => '#A3CD65',
            'showcasepanel-accentoverlay' => 'dark',
            'showcasepanel-pattern' => 'metal',
            'featurepanel-backgroundcolor' => '#B0B8AD',
            'featurepanel-overlay' => 'light',
            'featurepanel-accentcolor' => '#A3CD65',
            'featurepanel-accentoverlay' => 'dark',
            'featurepanel-pattern' => 'denim',
            'menu-overlay' => 'dark',
            'body-overlay' => 'light',
            'body-accentcolor' => '#A3CD65',
            'body-accentoverlay' => 'dark',
            'footerpanel-backgroundcolor' => '#8BB757',
            'footerpanel-overlay' => 'dark',
            'footerpanel-accentcolor' => '#A3CD65',
            'footerpanel-accentoverlay' => 'dark',
            'footerpanel-pattern' => 'leather'
        ),

        'preset4' => array (
            'name' => 'Preset 4',
            'logostyle' => 'style4',
            'headerpanel-backgroundcolor' => '#e0e0e0',
            'headerpanel-overlay' => 'light',
            'headerpanel-accentcolor' => '#A37389',
            'headerpanel-accentoverlay' => 'dark',
            'headerpanel-pattern' => 'paint-splatter',
            'showcasepanel-backgroundcolor' => '#30292C',
            'showcasepanel-overlay' => 'dark',
            'showcasepanel-accentcolor' => '#A37389',
            'showcasepanel-accentoverlay' => 'dark',
            'showcasepanel-pattern' => 'metal',
            'featurepanel-backgroundcolor' => '#B8B0AD',
            'featurepanel-overlay' => 'light',
            'featurepanel-accentcolor' => '#A37389',
            'featurepanel-accentoverlay' => 'dark',
            'featurepanel-pattern' => 'leather',
            'menu-overlay' => 'dark',
            'body-overlay' => 'light',
            'body-accentcolor' => '#A37389',
            'body-accentoverlay' => 'dark',
            'footerpanel-backgroundcolor' => '#A3798B',
            'footerpanel-overlay' => 'dark',
            'footerpanel-accentcolor' => '#A37389',
            'footerpanel-accentoverlay' => 'dark',
            'footerpanel-pattern' => 'leather'
        ),

        'preset5' => array (
            'name' => 'Preset 5',
            'logostyle' => 'style5',
            'headerpanel-backgroundcolor' => '#f0f0f0',
            'headerpanel-overlay' => 'light',
            'headerpanel-accentcolor' => '#D21200',
            'headerpanel-accentoverlay' => 'dark',
            'headerpanel-pattern' => 'paint-splatter',
            'showcasepanel-backgroundcolor' => '#222',
            'showcasepanel-overlay' => 'dark',
            'showcasepanel-accentcolor' => '#DB0B06',
            'showcasepanel-accentoverlay' => 'dark',
            'showcasepanel-pattern' => 'dustnscratches',
            'featurepanel-backgroundcolor' => '#aaa',
            'featurepanel-overlay' => 'light',
            'featurepanel-accentcolor' => '#D21200',
            'featurepanel-accentoverlay' => 'dark',
            'featurepanel-pattern' => 'textile',
            'menu-overlay' => 'light',
            'body-overlay' => 'light',
            'body-accentcolor' => '#D21200',
            'body-accentoverlay' => 'dark',
            'footerpanel-backgroundcolor' => '#990000',
            'footerpanel-overlay' => 'dark',
            'footerpanel-accentcolor' => '#E07474',
            'footerpanel-accentoverlay' => 'dark',
            'footerpanel-pattern' => 'noise'
        ),

        'preset6' => array (
            'name' => 'Preset 6',
            'logostyle' => 'style6',
            'headerpanel-backgroundcolor' => '#f0f0f0',
            'headerpanel-overlay' => 'light',
            'headerpanel-accentcolor' => '#F27C92',
            'headerpanel-accentoverlay' => 'dark',
            'headerpanel-pattern' => 'vertical-linen',
            'showcasepanel-backgroundcolor' => '#332C2C',
            'showcasepanel-overlay' => 'dark',
            'showcasepanel-accentcolor' => '#F27C92',
            'showcasepanel-accentoverlay' => 'dark',
            'showcasepanel-pattern' => 'woven-fabric',
            'featurepanel-backgroundcolor' => '#AA9DA2',
            'featurepanel-overlay' => 'light',
            'featurepanel-accentcolor' => '#F27C92',
            'featurepanel-accentoverlay' => 'dark',
            'featurepanel-pattern' => 'vertical-linen',
            'menu-overlay' => 'light',
            'body-overlay' => 'light',
            'body-accentcolor' => '#F27C92',
            'body-accentoverlay' => 'dark',
            'footerpanel-backgroundcolor' => '#E35F6A',
            'footerpanel-overlay' => 'dark',
            'footerpanel-accentcolor' => '#F27C92',
            'footerpanel-accentoverlay' => 'dark',
            'footerpanel-pattern' => 'leather'
        ),

        'preset7' => array (
            'name' => 'Preset 7',
            'logostyle' => 'style7',
            'headerpanel-backgroundcolor' => '#E5DFDA',
            'headerpanel-overlay' => 'light',
            'headerpanel-accentcolor' => '#74B7BD',
            'headerpanel-accentoverlay' => 'dark',
            'headerpanel-pattern' => 'noise',
            'showcasepanel-backgroundcolor' => '#383838',
            'showcasepanel-overlay' => 'dark',
            'showcasepanel-accentcolor' => '#74B7BD',
            'showcasepanel-accentoverlay' => 'dark',
            'showcasepanel-pattern' => 'denim',
            'featurepanel-backgroundcolor' => '#F1C094',
            'featurepanel-overlay' => 'light',
            'featurepanel-accentcolor' => '#333',
            'featurepanel-accentoverlay' => 'dark',
            'featurepanel-pattern' => 'wood',
            'menu-overlay' => 'dark',
            'body-overlay' => 'light',
            'body-accentcolor' => '#74B7BD',
            'body-accentoverlay' => 'dark',
            'footerpanel-backgroundcolor' => '#89B6B9',
            'footerpanel-overlay' => 'dark',
            'footerpanel-accentcolor' => '#74B7BD',
            'footerpanel-accentoverlay' => 'dark',
            'footerpanel-pattern' => 'leather'
        ),

        'preset8' => array (
            'name' => 'Preset 8',
            'logostyle' => 'style8',
            'headerpanel-backgroundcolor' => '#ddd',
            'headerpanel-overlay' => 'light',
            'headerpanel-accentcolor' => '#F7B92E',
            'headerpanel-accentoverlay' => 'dark',
            'headerpanel-pattern' => 'paint-splatter',
            'showcasepanel-backgroundcolor' => '#333',
            'showcasepanel-overlay' => 'dark',
            'showcasepanel-accentcolor' => '#F7B92E',
            'showcasepanel-accentoverlay' => 'dark',
            'showcasepanel-pattern' => 'denim',
            'featurepanel-backgroundcolor' => '#aaa',
            'featurepanel-overlay' => 'light',
            'featurepanel-accentcolor' => '#F7B92E',
            'featurepanel-accentoverlay' => 'dark',
            'featurepanel-pattern' => 'rough-fabric',
            'menu-overlay' => 'dark',
            'body-overlay' => 'light',
            'body-accentcolor' => '#F7B92E',
            'body-accentoverlay' => 'dark',
            'footerpanel-backgroundcolor' => '#999',
            'footerpanel-overlay' => 'dark',
            'footerpanel-accentcolor' => '#F7B92E',
            'footerpanel-accentoverlay' => 'dark',
            'footerpanel-pattern' => 'leather'
        ),

        'preset9' => array (
            'name' => 'Preset 9',
            'logostyle' => 'style9',
            'headerpanel-backgroundcolor' => '#404040',
            'headerpanel-overlay' => 'dark',
            'headerpanel-accentcolor' => '#E3231D',
            'headerpanel-accentoverlay' => 'dark',
            'headerpanel-pattern' => 'noise',
            'showcasepanel-backgroundcolor' => '#111',
            'showcasepanel-overlay' => 'dark',
            'showcasepanel-accentcolor' => '#E3231D',
            'showcasepanel-accentoverlay' => 'dark',
            'showcasepanel-pattern' => 'leather',
            'featurepanel-backgroundcolor' => '#505050',
            'featurepanel-overlay' => 'dark',
            'featurepanel-accentcolor' => '#E3231D',
            'featurepanel-accentoverlay' => 'dark',
            'featurepanel-pattern' => 'textile',
            'menu-overlay' => 'light',
            'body-overlay' => 'dark',
            'body-accentcolor' => '#E3231D',
            'body-accentoverlay' => 'dark',
            'footerpanel-backgroundcolor' => '#6b1212',
            'footerpanel-overlay' => 'dark',
            'footerpanel-accentcolor' => '#E3231D',
            'footerpanel-accentoverlay' => 'dark',
            'footerpanel-pattern' => 'grunge'
        ),

        'preset10' => array (
            'name' => 'Preset 10',
            'logostyle' => 'style10',
            'headerpanel-backgroundcolor' => '#333',
            'headerpanel-overlay' => 'dark',
            'headerpanel-accentcolor' => '#88CB29',
            'headerpanel-accentoverlay' => 'dark',
            'headerpanel-pattern' => 'noise',
            'showcasepanel-backgroundcolor' => '#080808',
            'showcasepanel-overlay' => 'dark',
            'showcasepanel-accentcolor' => '#88CB29',
            'showcasepanel-accentoverlay' => 'dark',
            'showcasepanel-pattern' => 'leather',
            'featurepanel-backgroundcolor' => '#404040',
            'featurepanel-overlay' => 'dark',
            'featurepanel-accentcolor' => '#88CB29',
            'featurepanel-accentoverlay' => 'dark',
            'featurepanel-pattern' => 'textile',
            'menu-overlay' => 'dark',
            'body-overlay' => 'dark',
            'body-accentcolor' => '#88CB29',
            'body-accentoverlay' => 'dark',
            'footerpanel-backgroundcolor' => '#444',
            'footerpanel-overlay' => 'dark',
            'footerpanel-accentcolor' => '#88CB29',
            'footerpanel-accentoverlay' => 'dark',
            'footerpanel-pattern' => 'grunge'
        ),

        'preset11' => array (
            'name' => 'Preset 11',
            'logostyle' => 'style11',
            'headerpanel-backgroundcolor' => '#f0f0f0',
            'headerpanel-overlay' => 'light',
            'headerpanel-accentcolor' => '#74B17A',
            'headerpanel-accentoverlay' => 'dark',
            'headerpanel-pattern' => 'planks',
            'showcasepanel-backgroundcolor' => '#2d3d33',
            'showcasepanel-overlay' => 'dark',
            'showcasepanel-accentcolor' => '#74B17A',
            'showcasepanel-accentoverlay' => 'dark',
            'showcasepanel-pattern' => 'dustnscratches',
            'featurepanel-backgroundcolor' => '#70240A',
            'featurepanel-overlay' => 'dark',
            'featurepanel-accentcolor' => '#74B17A',
            'featurepanel-accentoverlay' => 'dark',
            'featurepanel-pattern' => 'wood',
            'menu-overlay' => 'dark',
            'body-overlay' => 'light',
            'body-accentcolor' => '#74B17A',
            'body-accentoverlay' => 'dark',
            'footerpanel-backgroundcolor' => '#70240A',
            'footerpanel-overlay' => 'dark',
            'footerpanel-accentcolor' => '#74B17A',
            'footerpanel-accentoverlay' => 'dark',
            'footerpanel-pattern' => 'wood'
        ),

        'preset12' => array (
            'name' => 'Preset 12',
            'logostyle' => 'style12',
            'headerpanel-backgroundcolor' => '#f0f0f0',
            'headerpanel-overlay' => 'light',
            'headerpanel-accentcolor' => '#CC9A5E',
            'headerpanel-accentoverlay' => 'dark',
            'headerpanel-pattern' => 'metal',
            'showcasepanel-backgroundcolor' => '#322617',
            'showcasepanel-overlay' => 'dark',
            'showcasepanel-accentcolor' => '#CC9A5E',
            'showcasepanel-accentoverlay' => 'dark',
            'showcasepanel-pattern' => 'textile',
            'featurepanel-backgroundcolor' => '#b8a684',
            'featurepanel-overlay' => 'light',
            'featurepanel-accentcolor' => '#CC9A5E',
            'featurepanel-accentoverlay' => 'dark',
            'featurepanel-pattern' => 'leather',
            'menu-overlay' => 'dark',
            'body-overlay' => 'light',
            'body-accentcolor' => '#CC9A5E',
            'body-accentoverlay' => 'dark',
            'footerpanel-backgroundcolor' => '#222',
            'footerpanel-overlay' => 'dark',
            'footerpanel-accentcolor' => '#CC9A5E',
            'footerpanel-accentoverlay' => 'dark',
            'footerpanel-pattern' => 'leather'
        )

    )
);

$gantry_browser_params = array(
    'ie6' => array(
		'menu-enabled' => '0',
		'typography' => '0',
		'extensions' => '0',
		'fontsizer' => '0',
		'login' => '0',
		'popup' => '0',
		'morearticles' => '0',
		'totop-enabled' => '0',
		'smartload-enabled' => '0',
		'buildspans-enabled' => '0',
		'inputstyling' => '0'
    )
);

$gantry_belatedPNG = array('.png', '#rt-logo', '.component-block', '#rocket');
